//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnglishWorks
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountingForTasks
    {
        public int Number { get; set; }
        public int Task_ID { get; set; }
        public Nullable<int> Student_ID { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
    
        public virtual Students Students { get; set; }
        public virtual Tasks Tasks { get; set; }
    }
}
