//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnglishWorks
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EnglishKlassBDEntities : DbContext
    {
        public EnglishKlassBDEntities()
            : base("name=EnglishKlassBDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccountingForTasks> AccountingForTasks { get; set; }
        public virtual DbSet<ClassGroup> ClassGroup { get; set; }
        public virtual DbSet<Genders> Genders { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Students> Students { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tasks> Tasks { get; set; }
        public virtual DbSet<Teachers> Teachers { get; set; }
        public virtual DbSet<TypeTasks> TypeTasks { get; set; }
        public virtual DbSet<Users> Users { get; set; }


        private static EnglishKlassBDEntities _context;
        public static EnglishKlassBDEntities GetContext()
        {
            if (_context == null)
                _context = new EnglishKlassBDEntities();
            return _context;
        }
    }
}
